name: Scrape music chart

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 12 */2 * *"

jobs:
  start_scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run : npm i -g pnpm && pnpm i
    - name: Start scrape data of music chart
      run : pnpm scrape:music-chart
    - name: Commit and push if it changed
      run: |-
        git config user.name "satyawikananda"
        git config user.email "${{ secrets.EMAIL }}"
        git add -A
        timestamp=$(date -u)
        git commit -m "chore(scrape): Update scrape data of music chart" || exit 0
        git push
